### ISSUE TITLE
No output on Ubuntu 18.04

### ISSUE THREAD

**Issue by hellzhammer** [franzsilva/MLBuilderVSCode-Source#2]
So I just installed the extension and ml.net cli, 

![Screenshot from 2019-12-11 11-42-40](https://user-images.githubusercontent.com/36059809/70641260-5f75e000-1c0b-11ea-8abb-40572ee76718.png)
it goes through the setup fine. im able to input everything as i would in visual studio on windows. then after i enter directory for output,  you get the little pop up. but then literally nothing happens. ive tried giving it different build times 10 secs-60, tried using different directories, but nothing is ever added to the output folder. 

i used this on windows and it was perfectly fine, same data set, i can use the vs model builder to. same machine. 

edit: the issue is caused when installing mlnet, ubuntu 18.04 isnt setting the environment variable.

use this in the terminal and after mlnet works.
export PATH="$PATH:~/.dotnet/tools"

echo 'export PATH="$PATH:~/.dotnet/tools"' >> ~/.bashrc

**Comment by franzsilva** [comment]
Hi sorry for the delay. I was on vacations. I will look into this, I have a ubuntu 18.04 machine at home.

**Comment by franzsilva** [comment]
should be working now on versione 0.1.0
